### ISSUE TITLE
xlsx2yaml: Export to key/value pair in 'values' instead of a list

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/sxl-tools#4]
The 'values' should contain a key/value pair, and not an array. 

Transform this:
```
type:
            type: string
            description: |-
              Type of detector.
              loop: Inductive detector loop
              input: External input
            values:
            - loop
            - input
```

Into this:
```
type:
            type: string
            description: |-
              Type of detector.
            values:
              loop: Inductive detector loop
              input: External input
```

- [x] The 'values' should contain a key/value pair, and not an array.
- [x] The values can be fetched from description field. Check each line by "key: value", otherwise just use an empty value
- [x] Don't modify the description field in xlsx2yaml
- [x] yaml2rst also needs updating
- [x] yaml2xlsx also needs updating
